# services/models_config.yaml
models:
  - name: primary
    provider: azureopenai
    config:
      azure_openai_deployment_env: AZURE_OPENAI_DEPLOYMENT
      azure_openai_endpoint_env: AZURE_OPENAI_ENDPOINT
      azure_openai_api_key_env: AZURE_OPENAI_API_KEY
      azure_openai_model_env: AZURE_OPENAI_MODEL_NAME
      azure_openai_api_version_env: AZURE_OPENAI_API_VERSION
    model_info:
        family: gpt-4o
        function_calling: true
        json_output: true
        structured_output: false
        vision: true
